"""Initial ledger-first schema and database invariants."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None


def enum_type(*values, name):
    """Reuse shared PostgreSQL enum types across separately created tables."""
    if op.get_bind().dialect.name == "postgresql":
        enum = postgresql.ENUM(*values, name=name, create_type=False)
        enum.create(op.get_bind(), checkfirst=True)
        return enum
    return sa.Enum(*values, name=name)


def upgrade():
    bind = op.get_bind()
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('changes_description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('street_address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('kyc_status', enum_type('PENDING', 'VERIFIED', 'REJECTED', name='kycstatus'), nullable=True),
    sa.Column('kyc_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kyc_document_url', sa.String(length=255), nullable=True),
    sa.Column('customer_type', enum_type('PERSONAL', 'BUSINESS', name='customertype'), nullable=True),
    sa.Column('customer_status', enum_type('ACTIVE', 'FROZEN', 'CLOSED', name='customerstatus'), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', enum_type('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_kyc_status'), 'customers', ['kyc_status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', enum_type('ADMIN', 'COMPLIANCE', 'SUPPORT', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=False),
    sa.Column('account_type', enum_type('CHECKING', 'SAVINGS', 'CREDIT', name='accounttype'), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('account_status', enum_type('ACTIVE', 'FROZEN', 'CLOSED', name='accountstatus'), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('daily_limit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('monthly_limit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('transaction_limit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('daily_limit IS NULL OR daily_limit > 0', name='ck_accounts_daily_limit'),
    sa.CheckConstraint('monthly_limit IS NULL OR monthly_limit > 0', name='ck_accounts_monthly_limit'),
    sa.CheckConstraint('transaction_limit IS NULL OR transaction_limit > 0', name='ck_transaction_limit'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customer_id_account_number', 'accounts', ['customer_id', 'account_number'], unique=False)
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=True)
    op.create_index(op.f('ix_accounts_customer_id'), 'accounts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_accounts_is_internal'), 'accounts', ['is_internal'], unique=False)
    op.create_table('kyc_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', enum_type('PASSPORT', 'DRIVER_LICENSE', 'ID_CARD', 'NATIONAL_ID', name='documenttype'), nullable=False),
    sa.Column('document_number', sa.Text(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('document_front_url', sa.Text(), nullable=False),
    sa.Column('document_back_url', sa.Text(), nullable=True),
    sa.Column('selfie_url', sa.Text(), nullable=False),
    sa.Column('verification_status', enum_type('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='verificationstatus'), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rejection_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_document_valid', sa.Boolean(), nullable=True),
    sa.Column('is_selfie_match', sa.Boolean(), nullable=True),
    sa.Column('liveness_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_documents_customer_id'), 'kyc_documents', ['customer_id'], unique=False)
    op.create_index(op.f('ix_kyc_documents_verification_status'), 'kyc_documents', ['verification_status'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('card_type', sa.String(length=50), nullable=False),
    sa.Column('card_number_encrypted', sa.String(length=255), nullable=False),
    sa.Column('card_last_4', sa.String(length=4), nullable=False),
    sa.Column('expiry_month', sa.Integer(), nullable=False),
    sa.Column('expiry_year', sa.Integer(), nullable=False),
    sa.Column('cvv_encrypted', sa.String(length=255), nullable=False),
    sa.Column('card_status', enum_type('ACTIVE', 'FROZEN', 'CANCELLED', name='cardstatus'), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_virtual', sa.Boolean(), nullable=True),
    sa.Column('daily_limit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('monthly_limit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('daily_spent', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('monthly_spent', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('last_reset_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('card_holder_name', sa.String(length=255), nullable=False),
    sa.Column('card_design', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('daily_limit IS NULL OR daily_limit > 0', name='ck_cards_daily_limit'),
    sa.CheckConstraint('monthly_limit IS NULL OR monthly_limit > 0', name='ck_cards_monthly_limit'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_account_id'), 'cards', ['account_id'], unique=False)
    op.create_index(op.f('ix_cards_customer_id'), 'cards', ['customer_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_customer_id', sa.Uuid(), nullable=False),
    sa.Column('from_account_id', sa.Uuid(), nullable=False),
    sa.Column('to_account_id', sa.Uuid(), nullable=True),
    sa.Column('to_customer_id', sa.Uuid(), nullable=True),
    sa.Column('transaction_type', enum_type('REVERSAL', 'TRANSFER', 'PAYMENT', 'DEPOSIT', 'WITHDRAWAL', 'FEE', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('to_currency_code', sa.String(length=3), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('converted_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('fee_reason', sa.String(length=255), nullable=True),
    sa.Column('status', enum_type('PENDING', 'COMPLETED', 'FAILED', 'REVERSED', name='transactionstatus'), nullable=True),
    sa.Column('reverses_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('merchant_category', sa.String(length=50), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_transactions_positive_amount'),
    sa.CheckConstraint('fee_amount >= 0', name='ck_nonnegative_fee'),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['from_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['reverses_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['to_customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reverses_transaction_id')
    )
    op.create_index('idx_created_at', 'transactions', ['created_at'], unique=False)
    op.create_index('idx_from_account_id', 'transactions', ['from_account_id'], unique=False)
    op.create_index('idx_status', 'transactions', ['status'], unique=False)
    op.create_index('idx_to_account_id', 'transactions', ['to_account_id'], unique=False)
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_transactions_reference_number'), 'transactions', ['reference_number'], unique=True)
    op.create_table('aml_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('check_type', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', enum_type('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=True),
    sa.Column('flags_triggered', sa.JSON(), nullable=True),
    sa.Column('resolution', enum_type('PENDING', 'APPROVED', 'REVIEW', 'BLOCKED', name='amlresolution'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolution_notes', sa.String(length=500), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customer_id_risk', 'aml_checks', ['customer_id', 'risk_level'], unique=False)
    op.create_index('idx_resolution', 'aml_checks', ['resolution'], unique=False)
    op.create_index(op.f('ix_aml_checks_customer_id'), 'aml_checks', ['customer_id'], unique=False)
    op.create_index(op.f('ix_aml_checks_transaction_id'), 'aml_checks', ['transaction_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('entry_type', enum_type('DEBIT', 'CREDIT', name='entrytype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('source_account_id', sa.Uuid(), nullable=True),
    sa.Column('destination_account_id', sa.Uuid(), nullable=True),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('status', enum_type('PENDING', 'COMPLETED', 'REVERSED', name='ledgerentrystatus'), nullable=True),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_ledger_entries_positive_amount'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_account_id_entry_date', 'ledger_entries', ['account_id', 'entry_date'], unique=False)
    op.create_index('idx_customer_id', 'ledger_entries', ['customer_id'], unique=False)
    op.create_index('idx_transaction_id', 'ledger_entries', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_account_id'), 'ledger_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_customer_id'), 'ledger_entries', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_transaction_id'), 'ledger_entries', ['transaction_id'], unique=False)
    # ### end Alembic commands ###
    if bind.dialect.name == "postgresql":
        from pathlib import Path
        sql = (Path(__file__).parent / "invariants.sql").read_text()
        # asyncpg accepts one SQL command per execute; function bodies contain semicolons.
        for statement in sql.split("-- SPLIT"):
            if statement.strip():
                op.execute(statement.strip())
    elif bind.dialect.name == "sqlite":
        for table in ("ledger_entries", "audit_logs"):
            for action in ("UPDATE", "DELETE"):
                op.execute(f"CREATE TRIGGER immutable_{table}_{action} BEFORE {action} ON {table} "
                           "BEGIN SELECT RAISE(ABORT, 'Immutable record'); END")


def downgrade():
    raise RuntimeError("Financial records cannot be destroyed by an automatic downgrade; restore a reviewed backup")
